// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFx0FUEFcYnkNZJz--cfzlmXlwVk-lfAw',
    appId: '1:345554168629:web:5a53eb4533dfdf24797a7c',
    messagingSenderId: '345554168629',
    projectId: 'uas-19312134',
    authDomain: 'uas-19312134.firebaseapp.com',
    storageBucket: 'uas-19312134.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKyEeOgmwa2fTs8Ve0IpWuFTrIuhmtSw8',
    appId: '1:345554168629:android:d23f821c4471781b797a7c',
    messagingSenderId: '345554168629',
    projectId: 'uas-19312134',
    storageBucket: 'uas-19312134.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrTeEa8q2-R7KzW1ovYCNtJaCpRRDQKBc',
    appId: '1:345554168629:ios:7579a5ebc84481ea797a7c',
    messagingSenderId: '345554168629',
    projectId: 'uas-19312134',
    storageBucket: 'uas-19312134.appspot.com',
    iosClientId: '345554168629-r903ve8rtdt5ddaeb1ni0i5bf7kivv93.apps.googleusercontent.com',
    iosBundleId: 'com.uas19312134.uas19312134',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrTeEa8q2-R7KzW1ovYCNtJaCpRRDQKBc',
    appId: '1:345554168629:ios:a16f7cde3ce675ee797a7c',
    messagingSenderId: '345554168629',
    projectId: 'uas-19312134',
    storageBucket: 'uas-19312134.appspot.com',
    iosClientId: '345554168629-6a907kriit8kfkvil4t6phsavguid708.apps.googleusercontent.com',
    iosBundleId: 'com.uas19312134.uas19312134.RunnerTests',
  );
}
